// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jnxuxrrvcdtmhzwaoyru.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpueHV4cnJ2Y2R0bWh6d2FveXJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0ODM5NDIsImV4cCI6MjA1OTA1OTk0Mn0.GOGpIqDwOdAPIqbZkiwblCZUQLVSQJppFATc4pz_ZFg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);